export const _userList = [
  {
    id: '1',
    name: 'Leandro Furlam',
    role: 'UX Designer',
    status: 'Ativo',
    avatarUrl: 'https://minimal-assets-api.vercel.app/assets/images/avatars/avatar_1.jpg',
    given_name: 'Leandro',
    family_name: 'Furlam',
    email: 'email@email.com',
    phone_number: '+5599999999999',
    street: 'Avenida Anísio Fernandes Coelho',
    number: '1245',
    complement: 'Apto 301',
    district: 'Jardim da Penha',
    city: 'Vitória',
    state: 'Espírito Santo'
  },
  {
    id: '2',
    name: 'Lucian Obrien',
    role: 'Full Stack Designer',
    status: 'Ativo',
    city: 'Vitória',
    district: 'Jardim Camburi',
    avatarUrl: 'https://minimal-assets-api.vercel.app/assets/images/avatars/avatar_2.jpg',
  },
  {
    id: '3',
    name: 'Deja Brady',
    role: 'Backend Developer',
    status: 'Inativo',
    city: 'Vitória',
    district: 'Praia do Canto',
    avatarUrl: 'https://minimal-assets-api.vercel.app/assets/images/avatars/avatar_3.jpg',
  },
];
